= rails-encrypted-token
:source-highlighter: pygments

image:https://img.shields.io/gem/v/rails-encrypted-token.svg["Gem Version", link="https://rubygems.org/gems/rails-encrypted-token"]
image:https://img.shields.io/travis/riboseinc/rails-encrypted-token/master.svg["Build Status", link="https://travis-ci.org/riboseinc/rails-encrypted-token"]
image:https://img.shields.io/codecov/c/github/riboseinc/rails-encrypted-token.svg["Test Coverage", link="https://codecov.io/gh/riboseinc/rails-encrypted-token"]
image:https://img.shields.io/codeclimate/github/riboseinc/rails-encrypted-token.svg["Code Climate", link="https://codeclimate.com/github/riboseinc/rails-encrypted-token"]

`rails-encrypted-token` implements CSRF using the
https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)_Prevention_Cheat_Sheet#Encrypted_Token_Pattern[encrypted
token pattern].

Its primary advantage is that the server does not have to store any
session-related data.

== Usage

=== Installation

Then add this line to your application's `Gemfile`:

[source,ruby]
----
gem 'rails-encrypted-token', github: 'riboseinc/rails-encrypted-token'
----

And then execute:

----
bundle
----

Or install it yourself as:

----
gem install rails-encrypted-token
----

=== Getting started

Simply put a line in your `application_controller.rb` like so:

[source,ruby]
----
class ApplicationController < ActionController::Base
  protect_from_forgery using: :encrypted_token
end
----

== Configurations

(TODO)

[source,ruby]
----
class ApplicationController < ActionController::Base
  protect_from_forgery using: :encrypted_token
end
----


|===============================================================================

== Development

After checking out the repo, run `bin/setup` to install dependencies. Then, run
`rake spec` to run the tests. You can also run `bin/console` for an interactive
prompt that will allow you to experiment.

=== Contributing

Bug reports and pull requests are welcome on GitHub at
https://github.com/riboseinc/rails-encrypted-token. This project is intended to be a
safe, welcoming space for collaboration, and contributors are expected to
adhere to the http://contributor-covenant.org[Contributor Covenant] code of
conduct.

== License

The gem is available as open source under the terms of the
http://opensource.org/licenses/MIT[MIT License].

This repository contains a copy of GeoLite2 City database created by Maxmind,
and licensed on https://creativecommons.org/licenses/by-sa/4.0[CC BY-SA 4.0].
